apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
    {{- with .Values.image.imagePullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: docker-socket-volume
          hostPath:
            path: /var/run/docker.sock
            type: File
        - name: trivy-cache
          hostPath:
            path: /var/trivy/Library/Caches
            type: DirectoryOrCreate
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
          - name: AZP_URL
            value: "{{ .Values.azpUrl }}"
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azure-devops-agents-secret
                key: azpToken
          - name: AZP_POOL
            value: "{{ .Values.azpPool }}"
          - name: AZP_AGENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: docker-socket-volume
            mountPath: /var/run/docker.sock
          - name: trivy-cache
            mountPath: /root/.cache
          securityContext:
            privileged: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}