{{- if not .Values.azpAgent.secret.useExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.azpAgent.secret.name }}
  labels:
    {{- include "azure-pipelines-agent.labels" . | nindent 4 }}
type: Opaque
data:
  azpToken: {{ .Values.azpAgent.token | b64enc }}
{{- end }}